application: ical-gcal
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /feed/(.+)
  script: app.py
  secure: optional
